#!/usr/bin/env python3
"""Generate standalone Lark parser from grammar file."""

import hashlib
import subprocess
import sys
from pathlib import Path

project_root = Path(__file__).parent.parent.parent
calc_path = project_root / "packages" / "hex-sl-utils" / "src" / "hex_sl_utils" / "calc"
grammar_path = calc_path / "grammar.lark"
output_path = calc_path / "_calc_parser_standalone.py"

# Read and hash the grammar file
grammar_content = grammar_path.read_text()
grammar_hash = hashlib.sha256(grammar_content.encode()).hexdigest()

print(f"Generating standalone parser from {grammar_path}")
print(f"Grammar hash: {grammar_hash}")

# Generate the parser using Lark CLI
cmd = [
    sys.executable,
    "-m",
    "lark.tools.standalone",
    str(grammar_path),
    "-o",
    str(output_path),
    "-c",  # Enable compression
    "-s",
    "start",  # Start rule
]

result = subprocess.run(cmd, capture_output=True, text=True, check=False)

if result.returncode != 0:
    print(f"Error generating parser: {result.stderr}")
    sys.exit(1)

# Read the generated content and add our header with hash
generated_content = output_path.read_text()

header = f'''"""
THIS FILE IS AUTO-GENERATED - DO NOT EDIT

Generated by scripts/calc/generate_standalone_parser.py
To regenerate: devbox run build:calc

This is a pre-compiled Lark parser that eliminates runtime grammar parsing.

Grammar hash: {grammar_hash}
"""

'''

# The generated source intentionally retains Lark's original style.
output_path.write_text("# ruff: noqa\n" + header + generated_content)

print(f"✓ Generated standalone parser at {output_path}")
print(f"✓ Added grammar hash to header: {grammar_hash}")
