/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
/**
 * Union over all definable resource types
 */
export type Resource = Model | View;
/**
 * The unique identifier for this model.
 * This identifier is used as its reference and must be unique across all models in the project. Changing this identifier may invalidate existing references.
 */
export type EntityId = string;
/**
 * A table or view in the data connection to use as the base for this model.
 * One of `base_sql_query` or `base_sql_table` must be provided.
 */
export type BaseSqlTable = string | null;
/**
 * A SQL statement that produces a table to use as the base of this model.
 * One of `base_sql_query` or `base_sql_table` must be provided.
 */
export type BaseSqlQuery = string | null;
/**
 * The abstract data type of this dimension.
 */
export type DataType =
  | "number"
  | "string"
  | "timestamp_tz"
  | "timestamp_naive"
  | "date"
  | "boolean"
  | "null"
  | "other";
/**
 * A sql select column expression that produces a scalar for each row. This is often a column name.
 * One of `expr_sql` or `expr_calc` can be provided. If neither is provided, defaults to `expr_sql` being the `id` of this dimension.
 */
export type ExprSql = string | null;
/**
 * A [Hex calc formula](https://learn.hex.tech/docs/explore-data/cells/calculations) which produces a scalar for each row.
 */
export type ExprCalc = string | null;
/**
 * The visibility of this dimension.
 */
export type Visibility = "public" | "private" | "internal";
/**
 * An aggregation function.
 */
export type MeasureFuncName =
  | "count"
  | "count_distinct"
  | "sum"
  | "sum_boolean"
  | "avg"
  | "min"
  | "max"
  | "median"
  | "stddev"
  | "stddev_pop"
  | "variance"
  | "variance_pop";
/**
 * Specifies the dimension over which the `func` aggregation is applied.
 * This dimension can be specified as a referenced dimension ID, or an inline dimension. If `type` is unspecified in an inline dimension, it is assumed to be `number`.
 */
export type Of = string | ScalarExpressionDefaultNumber | null;
/**
 * An aggregating sql select expression that produces a scalar over a set of rows.
 */
export type FuncSql = string | null;
/**
 * An aggregating [Hex calc formula](https://learn.hex.tech/docs/explore-data/cells/calculations) which produces a scalar over a set of rows.
 */
export type FuncCalc = string | null;
/**
 * List of dimensions that determine row selection for aggregation.
 * Rows will be filtered to those with minimum or maximum values of these dimensions.
 * Limited to a single dimension.
 *
 * @minItems 1
 * @maxItems 1
 */
export type SemiAdditiveOver = [SemiAdditiveOverMember];
/**
 * Whether to select rows with the minimum or maximum dimension value.
 * If omitted, defaults to 'max'.
 */
export type Pick = "min" | "max";
/**
 * List of dimension identifiers to group by when determining min/max values.
 * The semi-additive filtering will be applied within each group.
 */
export type SemiAdditiveGroupings = string[];
/**
 * The cardinality of the join, from the base model to the target.
 * This is declared to ensure Hex can properly invoke fan-out prevention.
 */
export type RelationType = "many_to_one" | "one_to_one" | "one_to_many";
/**
 * User-facing display name for this content group.
 * If omitted, defaults to the name of the `relation` or `base`.
 */
export type Name = string | null;
/**
 * User-facing description for this content group.
 * If omitted, defaults to the description of the `relation` or `base`.
 */
export type Description = string | null;
/**
 * The list of dimensions at this level to include.
 * The wildcard `...` can be used to include all dimensions at this level. To omit an item, prefix it with `~`.
 */
export type Dimensions = "..." | (string | ViewContentDimensionItem)[];
/**
 * The list of measures at this level to include.
 * The wildcard `...` can be used to include all measures at this level. To omit an item, prefix it with `~`.
 */
export type Measures = "..." | (string | ViewContentMeasureItem)[];
/**
 * A semantic model represents a rectangle of data and its capabilities.
 */
export interface Model {
  id: EntityId;
  /**
   * The type of this resource. `model` for data models, `view` for views.
   */
  type?: "model";
  base_sql_table?: BaseSqlTable;
  base_sql_query?: BaseSqlQuery;
  /**
   * A dimension represents a selectable column expression.
   * These can be physical columns, complex SQL snippets, or formulas.
   */
  dimensions?: Dimension[];
  /**
   * A measure represents a aggregated expression.
   */
  measures?: Measure[];
  /**
   * A relation defines a link between two models, aka a "join".
   * The properties of a relation can be referenced with dot-syntax within a bracket reference, such as `${relation_id.dimension_id}`.
   */
  relations?: Relation[];
  /**
   * The user-facing display name for this model.
   * If omitted, defaults to the sentence-case value of `id`.
   */
  name?: string;
  /**
   * The user-facing description of this model.
   */
  description?: string;
  visibility?: Visibility;
}
/**
 * A dimension represents a selectable column expression.
 *
 * These can be physical columns, complex SQL snippets, or formulas.
 */
export interface Dimension {
  id: EntityId;
  type: DataType;
  expr_sql?: ExprSql;
  expr_calc?: ExprCalc;
  /**
   * If true, this dimension is unique for all rows in this model.
   * This dimension may be used in the construction of primary keys.
   */
  unique?: boolean;
  /**
   * The user-facing display name for this dimension.
   * If omitted, defaults to the sentence-case value of `id`.
   */
  name?: string;
  /**
   * The user-facing description of this dimension.
   */
  description?: string;
  visibility?: Visibility;
}
/**
 * A measure represents a aggregated expression.
 */
export interface Measure {
  id: EntityId;
  /**
   * A standard aggregation function to use.
   * One of `func`+`of`, `func_sql` or `func_calc` must be provided.
   */
  func?: MeasureFuncName | null;
  of?: Of;
  func_sql?: FuncSql;
  func_calc?: FuncCalc;
  type?: DataType;
  /**
   * A list of boolean dimensions which must be true for a row to be included in the measure's aggregation.
   * Only supported for `func` measures.
   * These dimensions can be specified as a referenced dimension ID, or an inline dimension. If `type` is unspecified in an inline dimension, it is assumed to be `boolean`.
   */
  filters?: (string | ScalarExpressionDefaultBoolean)[];
  /**
   * The user-facing display name for this measure.
   * If omitted, defaults to the sentence-case value of `id`.
   */
  name?: string;
  /**
   * The user-facing description of this measure.
   */
  description?: string;
  visibility?: Visibility;
  /**
   * Semi-additive aggregation that selects specific rows before calculation.
   * Filters to minimum or maximum values of the specified dimension, then aggregates only those rows.
   *
   */
  semi_additive?: SemiAdditive | null;
}
export interface ScalarExpressionDefaultNumber {
  type?: DataType;
  expr_sql?: ExprSql;
  expr_calc?: ExprCalc;
}
export interface ScalarExpressionDefaultBoolean {
  type?: DataType;
  expr_sql?: ExprSql;
  expr_calc?: ExprCalc;
}
/**
 * A semi-additive specification controls how measures aggregate over specific
 * dimensions.
 *
 * Semi-additive measures are useful for metrics like account balances or inventory
 * levels, where you want the most recent value within each group rather than
 * summing all values.
 */
export interface SemiAdditive {
  over?: SemiAdditiveOver;
  groupings?: SemiAdditiveGroupings;
}
/**
 * A criteria for determining the rows to include in the semi-additive measure.
 *
 * Defines which dimension to use for row selection and how to select the rows.
 */
export interface SemiAdditiveOverMember {
  /**
   * The identifier of the dimension to use for row selection.
   */
  dimension: string;
  pick?: Pick;
}
/**
 * A relation defines a link between two models, aka a "join".
 *
 * The properties of a relation can be referenced with dot-syntax within a
 * bracket reference, such as `${relation_id.dimension_id}`.
 */
export interface Relation {
  id: EntityId;
  target?: EntityId;
  type: RelationType;
  /**
   * The SQL condition to join the base model to a target.
   * Within this snippet, all dimensions and relations (including this one) are in scope for `${ }` interpolation.
   */
  join_sql: string;
  visibility?: Visibility;
}
/**
 * A semantic view represents a curated set of model properties and join paths.
 *
 * Views can be used to define a fit-for-purpose exposure of models and their
 * properties, providing a cleaner sandbox for users and agents interacting with
 * your semantic project.
 */
export interface View {
  id: EntityId;
  /**
   * The type of this resource. `model` for data models, `view` for views.
   */
  type?: "view";
  /**
   * The ID of the model that this view is based on.
   */
  base: string;
  /**
   * The contents of the view.
   */
  contents: ViewContentsGroup[];
  /**
   * The user-facing display name for this view.
   * If omitted, defaults to the sentence-case value of `id`.
   */
  name?: string;
  /**
   * The user-facing description of this view.
   */
  description?: string;
}
export interface ViewContentsGroup {
  relation?: Relation;
  name?: Name;
  description?: Description;
  dimensions?: Dimensions;
  measures?: Measures;
  /**
   * Content nested within this group.
   */
  contents?: ViewContentsGroup[];
}
/**
 * A dimension included within a view content group.
 */
export interface ViewContentDimensionItem {
  /**
   * The ID path to the dimension to include.
   */
  dimension: string;
  name?: Name;
  description?: Description;
}
/**
 * A measure included within a view content group.
 */
export interface ViewContentMeasureItem {
  /**
   * The ID path to the measure to include.
   */
  measure: string;
  name?: Name;
  description?: Description;
}
