import json
from pathlib import Path
from urllib.request import urlopen
from xml.etree import ElementTree

WINDOWS_ZONES_URL = "https://raw.githubusercontent.com/unicode-org/cldr/main/common/supplemental/windowsZones.xml"
HEADER = "# DO NOT EDIT -- generated by scripts/make_iana_win_mapping.py"

# Define the root directory
here = Path(__file__).absolute().parent
root = here.parent.parent


def main() -> None:
    doc_root = ElementTree.fromstring(urlopen(WINDOWS_ZONES_URL).read())  # noqa: S310, S314 (trusted source)
    # Plain UTC is supported by Windows, but not in the windowsZones.xml file
    iana_to_windows = {"UTC": "UTC"}
    for mapping in doc_root.findall("./windowsZones/mapTimezones/mapZone"):
        for iana in mapping.attrib["type"].split():
            iana_to_windows[iana] = mapping.attrib["other"]

    # Define the new directory path
    py_path = root / "src" / "hex_sl" / "timezones" / "windows_zones.py"
    py_path.write_text(
        f"""{HEADER}

IANA_TO_WINDOWS = {json.dumps(iana_to_windows, indent=4)}
"""
    )


if __name__ == "__main__":
    main()
