"""Generate the IANA-to-Windows timezone mapping from Unicode CLDR."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from urllib.request import urlopen
from xml.etree import ElementTree

CLDR_COMMIT = "9d96f340ab145003b3e6d12d95ffb16f19a8a529"
WINDOWS_ZONES_URL = (
    "https://raw.githubusercontent.com/unicode-org/cldr/"
    f"{CLDR_COMMIT}/common/supplemental/windowsZones.xml"
)
HEADER = "# DO NOT EDIT -- generated by `devbox run build:timezones`."
PROJECT_ROOT = Path(__file__).resolve().parents[2]
OUTPUT_PATH = (
    PROJECT_ROOT
    / "packages"
    / "hex-sl-utils"
    / "src"
    / "hex_sl_utils"
    / "timezone"
    / "iana_to_windows.py"
)


def render_mapping() -> str:
    with urlopen(WINDOWS_ZONES_URL, timeout=30) as response:
        document = ElementTree.fromstring(response.read())

    iana_to_windows = {"UTC": "UTC"}
    for mapping in document.findall("./windowsZones/mapTimezones/mapZone"):
        for iana_zone in mapping.attrib["type"].split():
            iana_to_windows[iana_zone] = mapping.attrib["other"]

    serialized_mapping = json.dumps(iana_to_windows, indent=4)
    serialized_mapping = serialized_mapping.removesuffix("\n}") + ",\n}"

    return f"""{HEADER}

IANA_TO_WINDOWS = {serialized_mapping}
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail instead of writing when the generated mapping is stale",
    )
    args = parser.parse_args()
    generated = render_mapping()

    if args.check:
        if not OUTPUT_PATH.exists() or OUTPUT_PATH.read_text() != generated:
            print(
                "IANA-to-Windows timezone mapping is stale; "
                "run `devbox run build:timezones`.",
                file=sys.stderr,
            )
            raise SystemExit(1)
        print("IANA-to-Windows timezone mapping is current.")
        return

    OUTPUT_PATH.write_text(generated)
    print(f"Wrote {OUTPUT_PATH.relative_to(PROJECT_ROOT)}")


if __name__ == "__main__":
    main()
