from hex_sl_utils.calc.ast.functions.aggs import (
    FuncAvg,
    FuncCount,
    FuncCountDistinct,
    FuncMax,
    FuncMedian,
    FuncMin,
    FuncPercentile,
    FuncPercentileApprox,
    FuncStddev,
    FuncStddevPop,
    FuncSum,
    FuncSumBoolean,
    FuncVariance,
    FuncVariancePop,
)
from hex_sl_utils.calc.ast.functions.base import FuncBase
from hex_sl_utils.calc.ast.functions.cast import (
    FuncToBoolean,
    FuncToDate,
    FuncToDatetime,
    FuncToNumber,
    FuncToText,
)
from hex_sl_utils.calc.ast.functions.control import (
    FuncCoalesce,
    FuncIf,
    FuncIsFinite,
    FuncIsNull,
    FuncIsOneOf,
    FuncSwitch,
)
from hex_sl_utils.calc.ast.functions.date_part import (
    FuncDatetimeToEpochMs,
    FuncDay,
    FuncDayOfWeek,
    FuncEpochMsToDatetime,
    FuncHour,
    FuncMillisecond,
    FuncMinute,
    FuncMonth,
    FuncQuarter,
    FuncSecond,
    FuncYear,
)
from hex_sl_utils.calc.ast.functions.date_trunc import (
    FuncTruncDay,
    FuncTruncHour,
    FuncTruncMillisecond,
    FuncTruncMinute,
    FuncTruncMonth,
    FuncTruncQuarter,
    FuncTruncSecond,
    FuncTruncWeek,
    FuncTruncWeekMonday,
    FuncTruncYear,
)
from hex_sl_utils.calc.ast.functions.function import TaggedFuncExprUnion, func_for_name
from hex_sl_utils.calc.ast.functions.instant import FuncNow, FuncToday
from hex_sl_utils.calc.ast.functions.internal import (
    FuncChartToDatetime,
    FuncChartToNumber,
)
from hex_sl_utils.calc.ast.functions.string import (
    FuncConcat,
    FuncContains,
    FuncEndsWith,
    FuncLeft,
    FuncLength,
    FuncLower,
    FuncRight,
    FuncSplitPart,
    FuncStartsWith,
    FuncSubstitute,
    FuncUpper,
)
from hex_sl_utils.calc.ast.functions.unary_math import (
    FuncAbs,
    FuncCeil,
    FuncCos,
    FuncCot,
    FuncExp,
    FuncFloor,
    FuncRound,
    FuncSin,
    FuncSqrt,
    FuncTan,
)

__all__ = [  # noqa: RUF022
    "TaggedFuncExprUnion",
    "func_for_name",
    # Base class
    "FuncBase",
    # String functions
    "FuncConcat",
    "FuncLeft",
    "FuncRight",
    "FuncSubstitute",
    "FuncUpper",
    "FuncLower",
    "FuncContains",
    "FuncStartsWith",
    "FuncEndsWith",
    "FuncLength",
    "FuncSplitPart",
    # Unary math functions
    "FuncSqrt",
    "FuncAbs",
    "FuncCeil",
    "FuncExp",
    "FuncFloor",
    "FuncRound",
    "FuncCos",
    "FuncSin",
    "FuncTan",
    "FuncCot",
    # Aggregate functions
    "FuncMin",
    "FuncMax",
    "FuncAvg",
    "FuncCount",
    "FuncSum",
    "FuncSumBoolean",
    "FuncPercentile",
    "FuncPercentileApprox",
    "FuncStddev",
    "FuncStddevPop",
    "FuncVariance",
    "FuncVariancePop",
    "FuncMedian",
    "FuncCountDistinct",
    # Control functions
    "FuncIf",
    "FuncSwitch",
    "FuncIsNull",
    "FuncCoalesce",
    "FuncIsFinite",
    "FuncIsOneOf",
    # Cast functions
    "FuncToDatetime",
    "FuncToDate",
    "FuncToNumber",
    "FuncToText",
    "FuncToBoolean",
    # Date part functions
    "FuncYear",
    "FuncQuarter",
    "FuncMonth",
    "FuncDay",
    "FuncDayOfWeek",
    "FuncHour",
    "FuncMinute",
    "FuncSecond",
    "FuncMillisecond",
    "FuncEpochMsToDatetime",
    "FuncDatetimeToEpochMs",
    # Date trunc functions
    "FuncTruncYear",
    "FuncTruncQuarter",
    "FuncTruncMonth",
    "FuncTruncWeek",
    "FuncTruncWeekMonday",
    "FuncTruncDay",
    "FuncTruncHour",
    "FuncTruncMinute",
    "FuncTruncSecond",
    "FuncTruncMillisecond",
    # Instant functions
    "FuncNow",
    "FuncToday",
    # Internal functions
    "FuncChartToNumber",
    "FuncChartToDatetime",
]
