-- === CALCS ===
-- year(ts)
-- quarter(ts)
-- month(ts)
-- day(ts)
-- dayofweek(ts)
-- hour(ts)
-- minute(ts)
-- second(ts)
-- millisecond(ts)

-- === BIGQUERY ===
EXTRACT(YEAR FROM `ts`);
EXTRACT(QUARTER FROM `ts`);
EXTRACT(MONTH FROM `ts`);
EXTRACT(DAY FROM `ts`);
EXTRACT(DAYOFWEEK FROM `ts`);
EXTRACT(HOUR FROM `ts`);
EXTRACT(MINUTE FROM `ts`);
CAST(TRUNC(EXTRACT(SECOND FROM `ts`)) AS INT64);
MOD(EXTRACT(MILLISECOND FROM `ts`), 1000);

-- === CLICKHOUSE ===
EXTRACT(YEAR FROM "ts");
EXTRACT(QUARTER FROM "ts");
EXTRACT(MONTH FROM "ts");
EXTRACT(DAY FROM "ts");
toDayOfWeek("ts", 3);
EXTRACT(HOUR FROM "ts");
EXTRACT(MINUTE FROM "ts");
CAST(EXTRACT(SECOND FROM "ts") AS Nullable(Int32));
EXTRACT(MILLISECOND FROM "ts") % 1000;

-- === DUCKDB ===
EXTRACT(YEAR FROM "ts");
EXTRACT(QUARTER FROM "ts");
EXTRACT(MONTH FROM "ts");
EXTRACT(DAY FROM "ts");
EXTRACT(DAYOFWEEK FROM "ts") + 1;
EXTRACT(HOUR FROM "ts");
EXTRACT(MINUTE FROM "ts");
CAST(EXTRACT(SECOND FROM "ts") AS BIGINT);
EXTRACT('MILLISECOND' FROM "ts") % 1000;

-- === MSSQL ===
DATEPART(YEAR, [ts]);
DATEPART(QUARTER, [ts]);
DATEPART(MONTH, [ts]);
DATEPART(DAY, [ts]);
DATEPART(DW, [ts]);
DATEPART(HOUR, [ts]);
DATEPART(MINUTE, [ts]);
CAST(DATEPART(SECOND, [ts]) AS INTEGER);
DATEPART(MILLISECOND, [ts]) % 1000;

-- === MYSQL ===
EXTRACT(YEAR FROM `ts`);
EXTRACT(QUARTER FROM `ts`);
EXTRACT(MONTH FROM `ts`);
EXTRACT(DAY FROM `ts`);
DAYOFWEEK(`ts`);
EXTRACT(HOUR FROM `ts`);
EXTRACT(MINUTE FROM `ts`);
CAST(EXTRACT(SECOND FROM `ts`) AS SIGNED);
FLOOR(EXTRACT(microsecond FROM `ts`) / 1000);

-- === POSTGRES ===
EXTRACT(YEAR FROM "ts");
EXTRACT(QUARTER FROM "ts");
EXTRACT(MONTH FROM "ts");
EXTRACT(DAY FROM "ts");
EXTRACT(dow FROM "ts") + 1;
EXTRACT(HOUR FROM "ts");
EXTRACT(MINUTE FROM "ts");
CAST(FLOOR(EXTRACT('second' FROM "ts")) AS INT);
CAST(FLOOR(EXTRACT('millisecond' FROM "ts")) AS INT) % 1000;

-- === REDSHIFT ===
EXTRACT(YEAR FROM "ts");
EXTRACT(QUARTER FROM "ts");
EXTRACT(MONTH FROM "ts");
EXTRACT(DAY FROM "ts");
EXTRACT(dow FROM "ts") + 1;
EXTRACT(HOUR FROM "ts");
EXTRACT(MINUTE FROM "ts");
CAST(FLOOR(EXTRACT('second' FROM "ts")) AS INTEGER);
MOD(CAST(FLOOR(EXTRACT('millisecond' FROM "ts")) AS INTEGER), 1000);

-- === SNOWFLAKE ===
DATE_PART(YEAR, "ts");
DATE_PART(QUARTER, "ts");
DATE_PART(MONTH, "ts");
DATE_PART(DAY, "ts");
DATE_PART(DAYOFWEEK, "ts") + 1;
DATE_PART('hour', "ts");
DATE_PART('minute', "ts");
CAST(DATE_PART('second', "ts") AS BIGINT);
DATE_PART('epoch_millisecond', "ts") % 1000;

-- === SPARK ===
EXTRACT(YEAR FROM `ts`);
EXTRACT(QUARTER FROM `ts`);
EXTRACT(MONTH FROM `ts`);
EXTRACT(DAY FROM `ts`);
DAYOFWEEK(TO_DATE(`ts`));
EXTRACT(HOUR FROM `ts`);
EXTRACT(MINUTE FROM `ts`);
CAST(EXTRACT(SECOND FROM `ts`) AS BIGINT);
CAST(DATE_FORMAT(`ts`, 'SSS') AS INT);

-- === TRINO ===
EXTRACT(YEAR FROM "ts");
EXTRACT(QUARTER FROM "ts");
EXTRACT(MONTH FROM "ts");
EXTRACT(DAY FROM "ts");
DAY_OF_WEEK("ts") % 7 + 1;
EXTRACT(HOUR FROM "ts");
EXTRACT(MINUTE FROM "ts");
CAST(EXTRACT(SECOND FROM "ts") AS BIGINT);
MILLISECOND("ts");
