#!/usr/bin/env python3
"""Generate standalone Lark parser from grammar file."""

import hashlib
import subprocess
import sys
from pathlib import Path

# Find project root (2 levels up from scripts/grammar/)
project_root = Path(__file__).parent.parent.parent
grammar_path = project_root / "src/hex_sl/calc/grammar.lark"
output_path = project_root / "src/hex_sl/calc/_calc_parser_standalone.py"

# Read and hash the grammar file
grammar_content = grammar_path.read_text()
grammar_hash = hashlib.sha256(grammar_content.encode()).hexdigest()

print(f"Generating standalone parser from {grammar_path}")
print(f"Grammar hash: {grammar_hash}")

# Generate the parser using Lark CLI
cmd = [
    sys.executable,
    "-m",
    "lark.tools.standalone",
    str(grammar_path),
    "-o",
    str(output_path),
    "-c",  # Enable compression
    "-s",
    "start",  # Start rule
]

result = subprocess.run(cmd, capture_output=True, text=True, check=False)  # noqa: S603

if result.returncode != 0:
    print(f"Error generating parser: {result.stderr}")
    sys.exit(1)

# Read the generated content and add our header with hash
generated_content = output_path.read_text()

header = f'''"""
THIS FILE IS AUTO-GENERATED - DO NOT EDIT

Generated by scripts/grammar/generate_standalone_parser.py
To regenerate: pixi run generate-standalone-parser

This is a pre-compiled Lark parser that eliminates runtime grammar parsing.

Grammar hash: {grammar_hash}
"""

'''

# Write back with header
output_path.write_text(header + generated_content)

print(f"✓ Generated standalone parser at {output_path}")
print(f"✓ Added grammar hash to header: {grammar_hash}")
