#!/usr/bin/env python3
"""Generate standalone Lark parser from grammar file."""

import hashlib
import subprocess
import sys
from pathlib import Path

from lark import __version__ as lark_version

project_root = Path(__file__).parent.parent.parent
calc_source = project_root / "packages/hex-sl-utils/src/hex_sl_utils/calc"
grammar_path = calc_source / "grammar.lark"
output_path = calc_source / "_calc_parser_standalone.py"

grammar_content = grammar_path.read_text()
grammar_hash = hashlib.sha256(grammar_content.encode()).hexdigest()

print(f"Generating standalone parser from {grammar_path}")
print(f"Grammar hash: {grammar_hash}")

cmd = [
    sys.executable,
    "-m",
    "lark.tools.standalone",
    str(grammar_path),
    "-o",
    str(output_path),
    "-c",  # Enable compression
    "-s",
    "start",  # Start rule
]

result = subprocess.run(cmd, capture_output=True, text=True, check=False)

if result.returncode != 0:
    print(f"Error generating parser: {result.stderr}")
    sys.exit(1)

generated_content = output_path.read_text()

header = f'''"""
THIS FILE IS AUTO-GENERATED - DO NOT EDIT

Generated by scripts/calc-parser/generate_standalone_parser.py
To regenerate: devbox run build:calc-parser

This is a pre-compiled Lark parser that eliminates runtime grammar parsing.

Grammar hash: {grammar_hash}
Lark version: {lark_version}
"""

'''

output_path.write_text(header + generated_content)

print(f"✓ Generated standalone parser at {output_path}")
print(f"✓ Added grammar hash to header: {grammar_hash}")
print(f"✓ Added Lark version to header: {lark_version}")
